#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("key_0", 32, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("key_1", 32, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("key_2", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("key_3", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("inout_0_i", 32, hls_in, 4, "ap_ovld", "in_data", 1),
	Port_Property("inout_0_o", 32, hls_out, 4, "ap_ovld", "out_data", 1),
	Port_Property("inout_0_o_ap_vld", 1, hls_out, 4, "ap_ovld", "out_vld", 1),
	Port_Property("inout_1_i", 32, hls_in, 5, "ap_ovld", "in_data", 1),
	Port_Property("inout_1_o", 32, hls_out, 5, "ap_ovld", "out_data", 1),
	Port_Property("inout_1_o_ap_vld", 1, hls_out, 5, "ap_ovld", "out_vld", 1),
	Port_Property("inout_2_i", 32, hls_in, 6, "ap_ovld", "in_data", 1),
	Port_Property("inout_2_o", 32, hls_out, 6, "ap_ovld", "out_data", 1),
	Port_Property("inout_2_o_ap_vld", 1, hls_out, 6, "ap_ovld", "out_vld", 1),
	Port_Property("inout_3_i", 32, hls_in, 7, "ap_ovld", "in_data", 1),
	Port_Property("inout_3_o", 32, hls_out, 7, "ap_ovld", "out_data", 1),
	Port_Property("inout_3_o_ap_vld", 1, hls_out, 7, "ap_ovld", "out_vld", 1),
	Port_Property("iv_0_i", 32, hls_in, 8, "ap_ovld", "in_data", 1),
	Port_Property("iv_0_o", 32, hls_out, 8, "ap_ovld", "out_data", 1),
	Port_Property("iv_0_o_ap_vld", 1, hls_out, 8, "ap_ovld", "out_vld", 1),
	Port_Property("iv_1_i", 32, hls_in, 9, "ap_ovld", "in_data", 1),
	Port_Property("iv_1_o", 32, hls_out, 9, "ap_ovld", "out_data", 1),
	Port_Property("iv_1_o_ap_vld", 1, hls_out, 9, "ap_ovld", "out_vld", 1),
	Port_Property("iv_2_i", 32, hls_in, 10, "ap_ovld", "in_data", 1),
	Port_Property("iv_2_o", 32, hls_out, 10, "ap_ovld", "out_data", 1),
	Port_Property("iv_2_o_ap_vld", 1, hls_out, 10, "ap_ovld", "out_vld", 1),
	Port_Property("iv_3_i", 32, hls_in, 11, "ap_ovld", "in_data", 1),
	Port_Property("iv_3_o", 32, hls_out, 11, "ap_ovld", "out_data", 1),
	Port_Property("iv_3_o_ap_vld", 1, hls_out, 11, "ap_ovld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "aes16_bidir";
